### ISSUE TITLE
Set number of rows of mines to defuse (1, 2, or 3)

### ISSUE THREAD

**Issue by Neidley** [Neidley/mobile-mines#12]
User should be able to select how many rows of mines they would like to defuse: 1, 2, or 3.

They could be 3 buttons labeled Easy, Medium, Hard.

There should be one randomMine or explosive mine per row that results in a loss for the whole game.

**Comment by nickisaacs** [comment]
I'll pick this up

**Comment by nickisaacs** [comment]
Here you go!
https://github.com/Neidley/mobile-mines/pull/16

**Comment by Neidley** [comment]
Awesome man!
I threw some styling on it and pushed it to production 👍
