### ISSUE TITLE
randomMine should be reset when Play button is pressed

### ISSUE THREAD

**Issue by Neidley** [Neidley/mobile-mines#13]
randomMine selects a random number 1 - 5,
to determine which mine will be armed to explode if clicked.

Currently it is only reset upon window refresh,
but we also want it to be reset every time the play button is pressed.

This should be a good starting place, here in `Provider.js` where it is currently set within DEFAULT_STATE - 
```
const DEFAULT_STATE = {
  message: "Good Luck",
  minesRemaining: 4,
  gameEnded: false,
  randomMine: `mine_${Math.floor(Math.random() * 5) + 1}`,
  mines
};
```

**Comment by Neidley** [comment]
Thanks @nickisaacs ! :) 
It's not an essential feature and you did so much good work in the last contribution, I wanted to go ahead and merge what you'd done on your previous PR. 
I went back and forth on the need for this change, but I think it is nice to have the game be completely new this way with the press of the play button

**Comment by Neidley** [comment]
ps - You may need to be able to fix this faster than I could, (if not interested, absolutely don't worry about it cause it doesn't seem to affect gameplay and I can always open another Issue for it).
Upon page load, we're getting a console error:
```
index.js:2178 Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `Gameboard`. See https://fb.me/react-warning-keys for more information.
    in Mine (at Gameboard.js:67)
    in Gameboard (at Gameboard.js:88)
    in Unknown (at App.js:13)
    in div (at App.js:12)
    in div (at App.js:10)
    in App (at index.js:10)
    in Provider (at index.js:9)
```

**Comment by nickisaacs** [comment]
@Neidley 
https://github.com/Neidley/mobile-mines/pull/14
I've taken care of both the problems!

**Comment by Neidley** [comment]
Excellent work sir!
Your understanding of React and Object-Oriented Programming continues to impress 🥇

**Comment by nickisaacs** [comment]
Thanks for your kind words!
