### ISSUE TITLE
Prepare React app for Production

### ISSUE THREAD

**Issue by Neidley** [Neidley/mobile-mines#15]
Using dev tools React extension in Google Chrome, place cursor over the React Developer Tool icon in the extension bar. Click and see that:

```
This page is using the development build of React. 🚧

Note that the development build is not suitable for production. 
Make sure to use the production build before deployment.

Open the developer tools, and the React tab will appear to the right.
```

Here's a link with instructions to prepare a React app for production:
https://reactjs.org/docs/optimizing-performance.html#use-the-production-build

Once you make the change and everything's running locally,
1. Create a Pull-Request and include a screenshot of the React Developer Tool displaying that the app is running in production mode. 
2. Reference the PR in this Issue's chat and
3. Get your contribution merged!

**Comment by nickisaacs** [comment]
May I know how are you deploying to Heroku? AFAIK, it is already production ready. You just need the right command during deployment

**Comment by Neidley** [comment]
lol I couldn't figure it out in the documentation...
normally I just run `git push heroku master`

**Comment by Neidley** [comment]
reading this article now - https://hackernoon.com/deploying-any-react-app-to-heroku-1ee6db9b97d3

**Comment by nickisaacs** [comment]
@Neidley 
I recommend this: https://blog.heroku.com/deploying-react-with-zero-configuration

**Comment by Neidley** [comment]
Create-React-App Buildpack successfully added on Heroku's website. Easy Peasy!

**Comment by Neidley** [comment]
http://www.mobile-mines.com/
