### ISSUE TITLE
Change the play button color

### ISSUE THREAD

**Issue by Neidley** [Neidley/mobile-mines#2]
Go into src/App.css, line 50-57 should look like this:

```
.play {
  height: 60px;
  width: 60px;
  border-radius: 50%;
  text-decoration-color: #000000;
  text-size: 50px;
  background-color: #509010;
}
```

Please change `background-color` to something new.
Here's W3's color picker for reference: 
https://www.w3schools.com/colors/colors_picker.asp

**Comment by aizkhaj** [comment]
I will submit a PR to suit the design language of this app.

**Comment by aizkhaj** [comment]
@Neidley reference #10 for the PR. Thanks

**Comment by Neidley** [comment]
Thanks for your contribution @aizkhaj !
