### ISSUE TITLE
Play button should reload Gameboard component, not refresh page

### ISSUE THREAD

**Issue by Neidley** [Neidley/mobile-mines#3]
This will require implementing Redux.

Refer to src/components/Play.js, specifically the `.onClick(e)` function to alter the button behavior
after mapStateToProps and PropTypes have been added.

For information on these concepts, here's a good place to start:

https://redux.js.org/basics/usage-with-react

https://stackoverflow.com/questions/38202572/understanding-react-redux-and-mapstatetoprops

React JS / Redux Tutorial - 7 - mapStateToProps - 
https://www.youtube.com/watch?v=IIMUXbkKzW0

**Comment by nickisaacs** [comment]
Hi @Neidley 
I can help you with redux. Please let me know if I can pick this up, and provide me with necessary details

**Comment by Neidley** [comment]
Hey, thanks for your interest!
Go ahead and link a PR. Just follow the README installation instructions (except for the last step which i think is currently half a sentence lol).
There should be instructions on getting it running locally.
And Please feel free to fork this and create you're own `/client` click-game so we can add it to the arcade I'm hoping we can build. 👍

**Comment by nickisaacs** [comment]
@Neidley 
I've opened a PR: https://github.com/Neidley/mobile-mines/pull/11
I used the new context API instead of Redux(redux is a bit of an overkill for this requirement IMO). If you still need redux, let me know and I can do that as well.

**Comment by Neidley** [comment]
@nickisaacs 
Thank you for your contribution!
Please feel free to submit your own issues to this repo with improvements you'd like to see, bug handling, etc.
I've merged your changes into the production side on heroku. :)

**Comment by nickisaacs** [comment]
You're welcome! Sure, will do
